export enum PermissionCodeEnum {
  //   training sessions
  GET_TRAINING_SESSION = 'GET_TRAINING_SESSION',
  CREATE_TRAINING_SESSION = 'CREATE_TRAINING_SESSION',
  UPDATE_TRAINING_SESSION = 'UPDATE_TRAINING_SESSION', //only the creator
  DELETE_TRAINING_SESSION = 'DELETE_TRAINING_SESSION', //only the creator
  SYSTEM_UPDATE_TRAINING_SESSION = 'SYSTEM_UPDATE_TRAINING_SESSION',
  SYSTEM_DELETE_TRAINING_SESSION = 'SYSTEM_DELETE_TRAINING_SESSION',

  //   presence
  GET_PRESENCE = 'GET_PRESENCE',
  SYSTEM_GET_PRESENCE = 'SYSTEM_GET_PRESENCE',
  MAKE_PRESENCE = 'MAKE_PRESENCE',
  UPDATE_PRESENCE = 'UPDATE_PRESENCE', // only the maker
  DELETE_PRESENCE = 'DELETE_PRESENCE', // only the maker
  SYSTEM_UPDATE_PRESENCE = 'SYSTEM_UPDATE_PRESENCE',
  SYSTEM_DELETE_PRESENCE = 'SYSTEM_DELETE_PRESENCE', // only the admin can

  //   roles
  GET_ROLE = 'GET_ROLE',
  CREATE_ROLE = 'CREATE_ROLE',
  SYSTEM_CREATE_ROLE = 'SYSTEM_CREATE_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  SYSTEM_UPDATE_ROLE = 'SYSTEM_UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  //   permissions
  GET_PERMISSION = 'GET_PERMISSION',

  //   scopes
  GET_SCOPE = 'GET_SCOPE',

  //   admins
  GET_ADMIN = 'GET_ADMINS',
  CREATE_ADMIN = 'CREATE_ADMIN',
  SYSTEM_CREATE_ADMIN = 'SYSTEM_CREATE_ADMIN',
  SYSTEM_DELETE_ADMIN = 'SYSTEM_DELETE_ADMIN',

  //   players
  GET_PLAYER = 'GET_PLAYER',
  CREATE_PLAYER = 'CREATE_PLAYER',
  UPDATE_PLAYER = 'UPDATE_PLAYER',
  DELETE_PLAYER = 'DELETE_PLAYER',

  //   trainers
  GET_TRAINER = 'GET_TRAINER',
  CREATE_TRAINER = 'CREATE_TRAINER',
  UPDATE_TRAINER = 'UPDATE_TRAINER',
  DELETE_TRAINER = 'DELETE_TRAINER',

  //   teams
  GET_TEAM = 'GET_TEAM',
  CREATE_TEAM = 'CREATE_TEAM',
  UPDATE_TEAM = 'UPDATE_TEAM',
  DELETE_TEAM = 'DELETE_TEAM',

  //   categories
  GET_CATEGORY = 'GET_CATEGORY',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',
}
