// export enum PermissionCodeEnum {
//   //   training sessions
//   GET_TRAINING_SESSION = 'GET_TRAINING_SESSION',
//   CREATE_TRAINING_SESSION = 'CREATE_TRAINING_SESSION',
//   UPDATE_TRAINING_SESSION = 'UPDATE_TRAINING_SESSION', //only the creator
//   DELETE_TRAINING_SESSION = 'DELETE_TRAINING_SESSION', //only the creator
//   SYSTEM_UPDATE_TRAINING_SESSION = 'SYSTEM_UPDATE_TRAINING_SESSION',
//   SYSTEM_DELETE_TRAINING_SESSION = 'SYSTEM_DELETE_TRAINING_SESSION',

//   //   presence
//   GET_PRESENCE = 'GET_PRESENCE',
//   SYSTEM_GET_PRESENCE = 'SYSTEM_GET_PRESENCE',
//   MAKE_PRESENCE = 'MAKE_PRESENCE',
//   UPDATE_PRESENCE = 'UPDATE_PRESENCE', // only the maker
//   DELETE_PRESENCE = 'DELETE_PRESENCE', // only the maker
//   SYSTEM_UPDATE_PRESENCE = 'SYSTEM_UPDATE_PRESENCE',
//   SYSTEM_DELETE_PRESENCE = 'SYSTEM_DELETE_PRESENCE', // only the admin can

//   //   roles
//   GET_ROLE = 'GET_ROLE',
//   CREATE_ROLE = 'CREATE_ROLE',
//   SYSTEM_CREATE_ROLE = 'SYSTEM_CREATE_ROLE',
//   UPDATE_ROLE = 'UPDATE_ROLE',
//   SYSTEM_UPDATE_ROLE = 'SYSTEM_UPDATE_ROLE',
//   DELETE_ROLE = 'DELETE_ROLE',

//   //   permissions
//   GET_PERMISSION = 'GET_PERMISSION',

//   //   scopes
//   GET_SCOPE = 'GET_SCOPE',

//   //   admins
//   GET_ADMIN = 'GET_ADMINS',
//   CREATE_ADMIN = 'CREATE_ADMIN',
//   SYSTEM_CREATE_ADMIN = 'SYSTEM_CREATE_ADMIN',
//   SYSTEM_DELETE_ADMIN = 'SYSTEM_DELETE_ADMIN',

//   //   players
//   GET_PLAYER = 'GET_PLAYER',
//   CREATE_PLAYER = 'CREATE_PLAYER',
//   UPDATE_PLAYER = 'UPDATE_PLAYER',
//   DELETE_PLAYER = 'DELETE_PLAYER',

//   //   trainers
//   GET_TRAINER = 'GET_TRAINER',
//   CREATE_TRAINER = 'CREATE_TRAINER',
//   UPDATE_TRAINER = 'UPDATE_TRAINER',
//   DELETE_TRAINER = 'DELETE_TRAINER',

//   //   teams
//   GET_TEAM = 'GET_TEAM',
//   CREATE_TEAM = 'CREATE_TEAM',
//   UPDATE_TEAM = 'UPDATE_TEAM',
//   DELETE_TEAM = 'DELETE_TEAM',

//   //   categories
//   GET_CATEGORY = 'GET_CATEGORY',
//   CREATE_CATEGORY = 'CREATE_CATEGORY',
//   UPDATE_CATEGORY = 'UPDATE_CATEGORY',
//   DELETE_CATEGORY = 'DELETE_CATEGORY',

//   // dashboard
//   ADMIN_ACCESS = 'ADMIN_ACCESS',
//   PLAYER_ACCESS = 'PLAYER_ACCESS',
//   TRAINER_ACCESS = 'TRAINER_ACCESS',
// }

export enum PermissionCodeEnum {
  // training sessions
  GET_TRAINING_SESSION = '87g6hn32k0',
  CREATE_TRAINING_SESSION = 'd9fgb71h32',
  UPDATE_TRAINING_SESSION = '4e21kjn87f',
  DELETE_TRAINING_SESSION = '0p3l45m2qw',
  SYSTEM_UPDATE_TRAINING_SESSION = '2o1n4b1p65',
  SYSTEM_DELETE_TRAINING_SESSION = '1n6v32d4s8',

  // presence
  GET_PRESENCE = '9r3gjk5l90',
  SYSTEM_GET_PRESENCE = '3m1n4bg7f8',
  MAKE_PRESENCE = 'u8n0v32c41',
  UPDATE_PRESENCE = '6b32v09s3d',
  DELETE_PRESENCE = 'k7v34g2l1m',
  SYSTEM_UPDATE_PRESENCE = '4b89k3n1o2',
  SYSTEM_DELETE_PRESENCE = '0pln45j2m3',

  // roles
  GET_ROLE = '1n9p2m3h5f',
  CREATE_ROLE = '3n8d45m2q1',
  SYSTEM_CREATE_ROLE = '0p3l4k5h2f',
  UPDATE_ROLE = '4b87g39l5m',
  SYSTEM_UPDATE_ROLE = '2o1n3b4v65',
  DELETE_ROLE = '9r2n3b8s5d',

  // permissions
  GET_PERMISSION = 'u8n4b2v1o3',

  // scopes
  GET_SCOPE = '0p3l4k2j8s',

  // admins
  GET_ADMIN = '1n0p4g5h3f',
  CREATE_ADMIN = '9r2n3b1m8s',
  SYSTEM_CREATE_ADMIN = '0p3l4k2j9f',
  SYSTEM_DELETE_ADMIN = '4b6v32d8s9',

  // players
  GET_PLAYER = '5d2b4v3n8s',
  CREATE_PLAYER = '1n0p3l4m5q',
  UPDATE_PLAYER = '9r2n8s4k1m',
  DELETE_PLAYER = '3b2v9n4s5d',

  // trainers
  GET_TRAINER = '8s3k1m5j2n',
  CREATE_TRAINER = '2o1n3b4v6s',
  UPDATE_TRAINER = '4b7g1n9p5f',
  DELETE_TRAINER = '5j2m0p3l8k',

  // teams
  GET_TEAM = '9r1n3b4m2q',
  CREATE_TEAM = '7g8h5j4k3n',
  UPDATE_TEAM = '1n0p3l4m9q',
  DELETE_TEAM = '2o5j8k3n4m',

  // categories
  GET_CATEGORY = '1n0p3l4k2j',
  CREATE_CATEGORY = '2o4v5n3b1m',
  UPDATE_CATEGORY = '3b2v9n1m8s',
  DELETE_CATEGORY = '7g6h5j4k8l',

  // dashboard
  ADMIN_ACCESS = '9r8s3k1m2j',
  PLAYER_ACCESS = '1n0a4g5hf5',
  TRAINER_ACCESS = '2o3b1m5j9f',
}
